server:
  port: 8081
spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: 123
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    locations: classpath:db/migration
    enabled: true
shortener:
  host: localhost
